routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('paket-tour', 'PaketTourController');
Route::resource('paket-tour.harga', 'PaketTourHargaController');
Route::resource('jenis-kendaraan', 'JenisKendaraanController');
Route::resource('kendaraan', 'JenisKendaraanController');
Route::resource('reservasi', 'ReservasiController');
Route::resource('konfirmasi-pembayaran', 'KonfirmasiPembayaranController');
Route::resource('migrate', 'Admin\MigrateController');

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('admin')->group(function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('paket-tour', 'PaketTourController');
    Route::resource('jenis-kendaraan', 'JenisKendaraanController');
    Route::resource('kendaraan', 'KendaraanController');
    Route::resource('driver', 'DriverController');
    Route::resource('users', 'UserController');
    Route::resource('rekening', 'RekeningController');
    Route::resource('admin', 'AdminController');
    Route::resource('reservasi', 'Reservasi\ReservasiController');
    Route::resource('konfirmasi-pembayaran', 'KonfirmasiPembayaranController');
    Route::resource('reports', 'ReportController');
    Route::resource('sepeda-motor', 'SepedaMotorController');
});

Route::name('akun.')->prefix('akun')->middleware('auth')->group(function(){
    Route::resource('reservasi', 'ReservasiController');
});
Route::resource('akun', 'UserController');


//Route::group(function(){
    Route::get('login-admin', 'Auth\LoginAdminController@showLoginForm');
    Route::post('login-admin', 'Auth\LoginAdminController@login');
//});

Route::get('verify-email', 'Auth\VerifyEmailController@index');

app/Models/JenisKendaraan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class JenisKendaraan extends Model
{
    public $fillable = ['name' ,'description', 'short_description', 'price', 'seat'];

    public function kendaraan()
    {
        return $this->hasMany('App\Models\Kendaraan');
    }

    public function getImageUrl()
    {
        return Storage::url( $this->image );
    }

    public function getFormatedPrice()
    {
        return 'Rp. ' . number_format( $this->price, 0, ',', '.');
    }

    public function getNameWithPriceAttribute()
    {
        return $this->name . ' (' . $this->getFormatedPrice() . ' )';
    }
}

app/Http/Controllers/Admin/JenisKendaraanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\JenisKendaraan as Model;

class JenisKendaraanController extends Controller
{
    /**
     * Index
     */
    public function index()
    {
        $items = Model::paginate(15);
        return view('admin.jenis-kendaraan.index', compact('items') );
    }

    /**
     * Create
     */
    public function create()
    {
        $model = new Model();
        return view('admin.jenis-kendaraan.create', compact('model') ); 
    }

    /**
     * Store
     */
    public function store( Request $request )
    {
        if ( $request->user()->role != 'administrator' ) {
            flash('Hanya admin yang dapat melakukan perubahan.')->error();
            return redirect()->back();
        }

        $model = Model::create( $request->input() );

        if ( $image = $request->file('image') ) {
            $model->image = $image->store('jenis-kendaraan');
            $model->save();
        }

        flash('Data Berhasil disimpan')->success();
        return redirect()->back()->withInput();
    }

    /**
     * Edit
     */
    public function edit( $id_paket_wisata, Request $request )
    {
        $model = Model::findOrFail( $id_paket_wisata );
        return view('admin.jenis-kendaraan.edit', compact('model') );
    }

    /**
     * Update
     */
    public function update( $id_paket_wisata, Request $request )
    {
        if ( $request->user()->role != 'administrator' ) {
            flash('Hanya admin yang dapat melakukan perubahan.')->error();
            return redirect()->back();
        }

        $model = Model::findOrFail( $id_paket_wisata );

        $model->fill( $request->input() );
        $model->save();

        if ( $image = $request->file('image') ) {
            if ( $model->gambar ) {
                Storage::delete( $model->gambar );
            }
            $model->image = $image->store('jenis-kendaraan');
            $model->save();
        }

        flash('Data Berhasil disimpan')->success();

        return redirect()->back()->withInput();
    }

    /**
     * Destroy
     */
    public function destroy( $id_paket_wisata, Request $request )
    {   
        if ( $request->user()->role != 'administrator' ) {
            flash('Hanya admin yang dapat melakukan perubahan.')->error();
            return redirect()->back();
        }

        $model = Model::findOrFail( $id_paket_wisata );
        $model->delete();
        flash('Data Berhasil Dihapus')->success();
        return redirect()->route('admin.jenis-kendaraan.index');
    }
}

app/Http/Controllers/JenisKendaraanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\JenisKendaraan as Model;
use App\Models\Reservasi;
use Illuminate\Support\Facades\Storage;

class JenisKendaraanController extends Controller
{
    /**
     * Index
     */
    public function index( Request $request )
    {
        $query = Model::query()->with(['kendaraan']);

        if( $id = $request->input('id') ) {
            $query->where('id', $id);
        }


        if ( $min_seat = $request->input('min_seat') ) {
            $query->where('seat', '>=', $min_seat);
            $query->orderBy('seat', 'ASC');
        }

        if ( $available = $request->input('available') ) {
            $query->whereHas('kendaraan', function( $q ) use( $available ){
                return $q->whereNotIn('id', Reservasi::select('kendaraan_id')->whereNotNull('kendaraan_id')->where('tanggal_pickup', $available)->pluck('kendaraan_id')->toArray() );
            });

            $query->withCount('kendaraan');
        }

        if ( $request->ajax() ) {
            return response()->json( $query->paginate(15) );
        }

        $items = $query->paginate();

        return view('jenis-kendaraan.index', compact('items') );
    }

    public function show( $id )
    {
        $model = Model::findOrFail( $id );
        return view('jenis-kendaraan.show', compact('model') );
    }
}

resources/views/jenis-kendaraan/index.blade.php
@extends('layouts.app')

@section('content')

@include('elements.cover-medium', ['title' => 'Kendaraan', 'subtitle' => 'Pilih kendaraan untuk pergi ke manapun yang anda mau.'])

<section class="py-5">
    <div class="container">
        <div class="row">
            @foreach( $items as $item)
                <div class="col-md-3">
                    <div class="card">
                        <a href="{{ route('jenis-kendaraan.show', $item->id)}}">
                            <img class="card-img-top" src="{{ Storage::url( $item->image) }}" alt="Card image cap">
                        </a>
                        <div class="card-body">
                            <h4 class="h5 mb-0">{{ $item->name }}</h4>

                            <p class="mb-0">{{ $item->short_description }}</p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

</section>

@endsection

resources/views/jenis-kendaraan/show.blade.php
@extends('layouts.app')

@section('content')

<section id="cover" class="overlay-dark overlay-darken py-5 justify-content-center" style="background-size: cover; background-image: url('{{ $model->getImageUrl() ?: url('/img/cover-tour.jpg') }}')">
    <div class="container text-center text-white" style="position: relative; z-index: 1;">
        <div class="pt-5">
            <h1 class="text-white">{{ $model->name }}</h1>
            <div class="divider short p-2"></div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb pl-0 pt-0 justify-content-center bg-transparent text-light">
                    <li class="breadcrumb-item">
                        <a href="{{ url('/') }}">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ route('paket-tour.index') }}">Paket Wisata</a>
                    </li>
                    <li class="active breadcrumb-item ">
                        {{ $model->name }}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <article>

                    <figure>
                        <img src="{{ $model->getImageUrl() }}" class="img-fluid rounded">
                    </figure>
                    
                    <p>{!! $model->description !!}</p>
                </article>
            </div>
            <div class="col-md-4">
                <div class="card bg-primary text-light mb-3">
                    <div class="card-body text-center">
                        <div class="h2 border-bottom mb-0 text-white">{{ $model->getFormatedPrice() }}</div>
                        <span class="">Inc. Driver</span>
                    </div>
                </div>

                @if( request()->user() ) 
                    <button class="btn btn-primary btn-block btn-lg" data-toggle="modal" data-target="#Modal-Booking">
                        Booking Mobil Ini
                    </button>
                @else
                    <a href="{{ url('/register') }}" class="btn btn-primary btn-block btn-lg" >
                        Booking Mobil Ini
                    </a>
                @endif

                <div class="modal fade" tabindex="-1" role="dialog" id="Modal-Booking">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Reservasi: {{ $model->name }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form>
                                    <input type="hidden" name="jenis_kendaraan_id" value="{{ $model->id }}"/>
                                    <div class="form-group">
                                        <label>Nama</label>
                                        <input type="text" name="name" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" name="email" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label>Tanggal Tour</label>
                                        <input type="date" name="tanggal_pickup" value="{{ \Carbon\Carbon::now()->addDay()->format('Y-m-d') }}" class="form-control" />
                                    </div>
                                    <div class="form-group alamat-pickup">
                                        <label>Alamat Pickup</label>
                                        <textarea type="email" name="alamat_pickup" class="form-control"></textarea>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-text" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary submit booking-mobil">Selanjutnya</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" tabindex="-1" role="dialog" id="Modal-Booking-Konfirmasi">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Konfirmasi Booking</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="detail-booking">
                                    <div class="d-flex justify-content-center">
                                        <div class="spinner-border" role="status">
                                            <span class="sr-only">Loading...</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-text" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary submit">Booking</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@endsection