routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('paket-tour', 'PaketTourController');
Route::resource('paket-tour.harga', 'PaketTourHargaController');
Route::resource('jenis-kendaraan', 'JenisKendaraanController');
Route::resource('kendaraan', 'JenisKendaraanController');
Route::resource('reservasi', 'ReservasiController');
Route::resource('konfirmasi-pembayaran', 'KonfirmasiPembayaranController');
Route::resource('migrate', 'Admin\MigrateController');

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('admin')->group(function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('paket-tour', 'PaketTourController');
    Route::resource('jenis-kendaraan', 'JenisKendaraanController');
    Route::resource('kendaraan', 'KendaraanController');
    Route::resource('driver', 'DriverController');
    Route::resource('users', 'UserController');
    Route::resource('rekening', 'RekeningController');
    Route::resource('admin', 'AdminController');
    Route::resource('reservasi', 'Reservasi\ReservasiController');
    Route::resource('konfirmasi-pembayaran', 'KonfirmasiPembayaranController');
    Route::resource('reports', 'ReportController');
    Route::resource('sepeda-motor', 'SepedaMotorController');
});

Route::name('akun.')->prefix('akun')->middleware('auth')->group(function(){
    Route::resource('reservasi', 'ReservasiController');
});
Route::resource('akun', 'UserController');


//Route::group(function(){
    Route::get('login-admin', 'Auth\LoginAdminController@showLoginForm');
    Route::post('login-admin', 'Auth\LoginAdminController@login');
//});

Route::get('verify-email', 'Auth\VerifyEmailController@index');

app/Models/Reservasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Helper;

class Reservasi extends Model
{  
    public $fillable = ['name', 'alamat_pickup', 'jumlah_penumpang', 'tanggal_pickup', 'nomor_hp', 'email', 'jenis_kendaraan_id', 'paket_tour_id', 'status_reservasi_id', 'driver_id', 'harga_paket_tour', 'harga_jenis_kendaraan', 'kendaraan_id', 'waktu_selesai'];

    public static function boot()
    {
        parent::boot();

        self::creating(function(&$model){
            $model->total = $model->harga_paket_tour + $model->harga_jenis_kendaraan;

            return $model;
        });

        self::updating(function(&$model){
            $model->total = $model->harga_paket_tour + $model->harga_jenis_kendaraan;

            return $model;
        });
    }

    public function paketTour()
    {
        return $this->belongsTo('App\Models\PaketTour');
    }

    public function jenisKendaraan()
    {
        return $this->belongsTo('App\Models\JenisKendaraan');
    }

    public function kendaraan()
    {
        return $this->belongsTo('App\Models\Kendaraan');
    }
    
    public function driver()
    {
        return $this->belongsTo('App\Models\Driver');
    }

    public function statusReservasi()
    {
        return $this->belongsTo('App\Models\StatusReservasi');
    }

    public function konfirmasiPembayaran()
    {
        return $this->hasMany('App\Models\KonfirmasiPembayaran');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getFormatedTotal()
    {
        return Helper::formatMoney( $this->total );
    }
}

app/Http/Controllers/Admin/Reservasi/AssignDriverController.php
<?php

namespace App\Http\Controllers\Admin\Reservasi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Reservasi as Model;

class AssignDriveriController extends Controller
{
    /**
     * Update
     */
    public function update( $model_id, Request $request )
    {
        $model = Model::findOrFail( $model_id );

        $model->fill( $request->only(['driver_id']) );
        $model->save();

        // LOG ASSIGN Driver

        flash('Data Berhasil disimpan')->success();

        return redirect()->back()->withInput();
    }
}

app/Http/Controllers/Admin/Reservasi/AssignKendaraanController.php
<?php

namespace App\Http\Controllers\Admin\Reservasi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Reservasi as Model;

class AssignKendaraanController extends Controller
{
    /**
     * Update
     */
    public function update( $model_id, Request $request )
    {
        $model = Model::findOrFail( $model_id );

        $model->fill( $request->only(['kendaraan_id']) );
        $model->save();

        // LOG ASSIGN KENDARAAN

        flash('Data Berhasil disimpan')->success();

        return redirect()->back()->withInput();
    }
}

app/Http/Controllers/Admin/Reservasi/ReservasiController.php
<?php

namespace App\Http\Controllers\Admin\Reservasi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Reservasi as Model;
use App\Models\StatusReservasi;
use App\Models\Driver;
use App\Models\PaketTour;
use App\Models\JenisKendaraan;
use App\Models\Kendaraan;
use Mail;
use App\Mail\ReservasiStatusEmail;

class ReservasiController extends Controller
{
    /**
     * Index
     */
    public function index( Request $request )
    {
        $items = Model::with(['statusReservasi']);
        $status_reservasi = StatusReservasi::pluck('name', 'id');

        if( $search = $request->input('search') ) {
            $items->where('name', 'LIKE', "%". $search ."%");
        }

        if( $status_reservasi_id = $request->input('status_reservasi_id') ) {
            $items->where('status_reservasi_id', $status_reservasi_id);
        }

        $items = $items->paginate(15);
        return view('admin.reservasi.index', compact('items', 'status_reservasi') );
    }

    /**
     * Show
     */
    public function show( $id )
    {
        $drivers = Driver::pluck('name', 'id');
        $status_reservasi = StatusReservasi::pluck('name', 'id');
        $model = Model::with(['paketTour', 'jenisKendaraan', 'kendaraan', 'driver', 'konfirmasiPembayaran'])->findOrFail( $id );
        return view('admin.reservasi.show', compact('model', 'status_reservasi', 'drivers') );
    }

    /**
     * Create
     */
    public function create()
    {
        $paket_wisatas = PaketTour::pluck('name', 'id');
        $jenis_kendaraans = JenisKendaraan::all();
        $kendaraans = Kendaraan::all();
        $status_reservasi = StatusReservasi::pluck('name', 'id');
        $drivers = Driver::pluck('name', 'id');
        $model = new Model();
        return view('admin.reservasi.create', compact('model', 'paket_wisatas', 'jenis_kendaraans', 'status_reservasi', 'drivers', 'kendaraans') ); 
    }

    /**
     * Store
     */
    public function store( Request $request )
    {
        $paket_wisata = new Model( $request->input() );
        $paket_wisata->save();
        
        flash('Data Berhasil disimpan')->success();
        return redirect()->back()->withInput();
    }

    /**
     * Edit
     */
    public function edit( $id_reservasi, Request $request )
    {
        $model = Model::findOrFail( $id_reservasi );
        $drivers = Driver::pluck('name', 'id');
        $paket_wisatas = PaketTour::pluck('name', 'id');
        $jenis_kendaraans = JenisKendaraan::all();
        $kendaraans = collect([]);

        if ( $model->jenis_kendaraan_id ) {
            $kendaraans = $model->jenisKendaraan->kendaraan;
        } 
        
        $status_reservasi = StatusReservasi::pluck('name', 'id');
        return view('admin.reservasi.edit', compact('model', 'drivers', 'paket_wisatas', 'jenis_kendaraans', 'status_reservasi', 'kendaraans') );
    }

    /**
     * Update
     */
    public function update( $id_paket_wisata, Request $request )
    {
        
        $model = Model::findOrFail( $id_paket_wisata );
        
        if ( $request->input('status_reservasi_id') != $model->status_reservasi_id ) {
            Mail::to( $model->user )->send( new ReservasiStatusEmail($model));
        }

        $model->fill( $request->input() );
        $model->save();
 
        flash('Data Berhasil disimpan')->success();

        if ( $request->ajax() ) {
            return response()->json( $model );
        }

        return redirect()->back()->withInput();
    }

    /**
     * Destroy
     */
    public function destroy( $id_paket_wisata )
    {   
        $model = Model::findOrFail( $id_paket_wisata );
        $model->delete();
        flash('Data Berhasil Dihapus')->success();
        return redirect()->back();
    }
}

app/Http/Controllers/ReservasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Reservasi as Model;
use App\Models\Kendaraan;
use App\Models\PaketTour;
use App\Models\JenisKendaraan;
use Illuminate\Support\Facades\Storage;
use App\Mail\MenungguPembayaranEmail;
use \Mail;

class ReservasiController extends Controller
{

    /**
     * Index
     */
    public function index( Request $request )
    {
        $query = Model::query()->with(['paketTour', 'jenisKendaraan', 'kendaraan', 'driver', 'statusReservasi']);

        $items = $query->where('user_id', $request->user()->id )->paginate(15);

        return view('akun.reservasi.index', compact( 'items' ) );
    }

    /**
     * Store
     */
    public function store( Request $request )
    {
        $model = new Model( $request->input() );
        $model->kode_reservasi = date('y') . ( date('z') + 1 ) . ( Model::max('id') + 1 ) ;

        if ( $paket_wisata_id = $request->input('paket_tour_id') ) {
            $paket_wisata = PaketTour::findOrFail( $paket_wisata_id );
            $model->harga_paket_tour = $paket_wisata->getPrice( $model->jumlah_penumpang );
        }

        if ( $jenis_kendaraan_id = $request->input('jenis_kendaraan_id') ) {
            $jenis_kendaraan = JenisKendaraan::find( $jenis_kendaraan_id );
            $available_kendaraan = Kendaraan::where('jenis_kendaraan_id', $jenis_kendaraan->id)->availableAt( $model->tanggal_pickup )->first();

            if( ! $available_kendaraan ) {
                abort(422, 'Kendaraan tidak tersedia pada tanggal tersebut');
            }
            
            $model->kendaraan_id = $available_kendaraan->id;
            $model->harga_jenis_kendaraan = $jenis_kendaraan->price;
        }

        $model->user_id = $request->user() ? $request->user()->id : null;
        $model->total = (int)$model->harga_paket_wisata + (int)$model->harga_jenis_kendaraan;
        $model->save();
        
        Mail::to( $request->user()->email )->send( new MenungguPembayaranEmail( $model ) );

        return response()->json( $model );
    }

    public function show( $kode_reservasi, Request $request )
    {
        $model = Model::where('kode_reservasi', $kode_reservasi)->with(['paketTour', 'jenisKendaraan', 'driver'])->firstOrFail();

        if ( $request->ajax() ) {
            return response()->json( $model );
        }

        return view('reservasi.show', compact( 'model' ) );
    }
}

resources/views/akun/reservasi/index.blade.php
@extends('layouts.user')

@section('content')
    <div class="container">
        
        <h3>Reservasi</h3>
            @foreach( $items as $item)
                
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <span>
                                <a href="{{ route('reservasi.show', $item->kode_reservasi) }}">
                                    #{{ $item->kode_reservasi }}
                                </a>
                            </span>
                            <div class="badge badge-warning">
                                {{ $item->statusReservasi->name }}
                            </div>
                        </div>
                        <small>{{ $item->tanggal_pickup }}</small>
                    </div>
                    <div class="card-body">
                        <div class="paket-tour">
                            @if( $item->paketTour )
                                <div class="media mb-3">
                                    <img width="100" class="mr-2 rounded" src="{{ $item->paketTour->getImageUrl() }}" />
                                    <div class="media-body">
                                        <strong>{{ $item->paketTour->name }}</strong><br>
                                        <small>Rp. {{ Helper::formatMoney( $item->harga_paket_tour ) }}</small>
                                    </div>
                                </div>
                            @endif

                            @if( $item->jenisKendaraan )
                                <div class="media mb-3">
                                    <img width="100" class="mr-2 rounded" src="{{ $item->jenisKendaraan->getImageUrl() }}" />
                                    <div class="media-body">
                                        <strong>{{ $item->jenisKendaraan->name }}</strong><br>
                                        <small>Rp. {{ Helper::formatMoney( $item->harga_jenis_kendaraan ) }}</small>
                                    </div>
                                </div>
                            @endif

                            <hr>
                            <div class="d-flex justify-content-between align-items-center">
                                <strong>Rp. {{ Helper::formatMoney( $item->total ) }}</strong>

                                @if( $item->status_reservasi_id == 1)
                                    <a href="{{ route('konfirmasi-pembayaran.index',  ['reservasi_id' => $item->id]) }}" class="btn btn-sm btn-primary">Konfirmasi Pembayaran</a>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            
            @endforeach
        </div>
    </div>
@endsection